/******************************************************************************
* Copyright 2013-2013 LASIGE                                                  *
*                                                                             *
* Licensed under the Apache License, Version 2.0 (the "License"); you may     *
* not use this file except in compliance with the License. You may obtain a   *
* copy of the License at http://www.apache.org/licenses/LICENSE-2.0           *
*                                                                             *
* Unless required by applicable law or agreed to in writing, software         *
* distributed under the License is distributed on an "AS IS" BASIS,           *
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    *
* See the License for the specific language governing permissions and         *
* limitations under the License.                                              *
*                                                                             *
*******************************************************************************
* A Lexicon extender that gets synonyms from an aligned Ontology.             *
*                                                                             *
* @author Daniel Faria                                                        *
* @date 22-10-2013                                                            *
******************************************************************************/
package aml.ext;

import java.util.Set;

import aml.match.Alignment;
import aml.match.Mapping;
import aml.ontology.Lexicon;
import aml.ontology.Ontology;

public class AlignmentExtender
{
	
//Attributes
	
	//The type of lexical entry generated by this Lexicon extender
	private final String TYPE = "externalMatch";
	
//Constructors

	/**
	 * Constructs a new AlignmentExtender 
	 */
	public AlignmentExtender(){}

//Public Methods

	/**
	 * Extends the Lexicon of the given Ontology using the given Alignment
	 * @param o: the Ontology to extend
 	 * @param a: the Alignment to use for extension
	 */
	public void extendLexicon(Ontology o, Alignment a)
	{
		Lexicon l = o.getLexicon();
		Lexicon ext = a.getTarget().getLexicon();
		String source = a.getTarget().getURI();

		for(Mapping m : a)
		{
			int target = m.getTargetId();
			Set<String> names = ext.getNames(target);
			for(String n : names)
				l.add(m.getSourceId(), n, TYPE, source, m.getSimilarity() * ext.getWeight(n, target));
		}
	}
}